### ISSUE TITLE
Problems In VR

### ISSUE THREAD

**Issue by VirtualyMichael** [ImTiara/VRCMods#1]
I used to use this all the time but for the past few months it just throws an error
But it works on desktop so it would be nice if that could be fixed
This is regarding immersive touch

**Comment by VirtualyMichael** [comment]
this is for immersive touch

**Comment by ImTiara** [comment]
Hi.
It would help a lot if you would be more specific such as posting the error itself and/or explaining what exactly the issue is.
Are you using it together with Turbones?

**Comment by VirtualyMichael** [comment]
Just when I open it it says every avatar even ones that worked before don't work for immersive touch and when I was on desktop and it was on the error was gone and it did add it correctly. So I don't know what to tell you but that

**Comment by ImTiara** [comment]
If you are using Booth avatars, i noticed that some of them have their hand colliders on the arm instead of the wrist itself which causes ImmersiveTouch to not work on that avatar. If you own the avatar i suggest checking how the hand colliders are setup in Unity. ImmersiveTouch will accept any dynamic bone colliders as long as they are on the hands (wrist, fingers etc).
I assume this is the case because nobody else has reported this before and personally i don't have any issues related to this.

**Comment by VirtualyMichael** [comment]
Well as I said it works on same avatars when im on desktop so it could be a full body thing if you can check on that
